# .github/workflows/build.yml

name: Build & Release

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.pkg.outputs.version }}
      should_build: ${{ steps.check_tag.outputs.exists == 'false' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Get version from package.json
        id: pkg
        run: echo "version=v$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Check if tag exists
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/${{ steps.pkg.outputs.version }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "> Tag ${{ steps.pkg.outputs.version }} already exists, skipping build."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "> Tag ${{ steps.pkg.outputs.version }} does not exist, proceeding with build."
          fi
        shell: bash

  build:
    needs: setup
    if: needs.setup.outputs.should_build == 'true'
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        shell: bash
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            pnpm electron:build --mac --publish never
          elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            pnpm electron:build --linux --publish never
          else
            pnpm electron:build --win --publish never
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chromini-${{ matrix.os }}
          path: |
            dist/*.dmg
            dist/*.zip
            dist/*.AppImage
            dist/*.tar.gz
            dist/*.exe
          if-no-files-found: error

  release:
    needs: [setup, build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create tag
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ needs.setup.outputs.version }}
          git push origin ${{ needs.setup.outputs.version }}

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.setup.outputs.version }}
          name: Release ${{ needs.setup.outputs.version }}
          files: artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}